const BLANK = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='

export const KEY_PAIRS = [
  { sw: 'Sw_react',      cap: 'React',        logo: '/Skills/react.png',        label: 'React',        hoverColor: '#61DAFB', desc: 'React is a declarative, component-based UI library developed by Meta for building fast, interactive interfaces. It uses a virtual DOM diffing algorithm to minimize repaints, and its composable component model makes large-scale frontend architecture maintainable and testable.' },
  { sw: 'Sw_threejs',    cap: 'Threejs',      logo: '/Skills/threedotjs.png',   label: 'Three.js',     hoverColor: '#706e6e', desc: 'Three.js is a JavaScript library that abstracts the complexity of WebGL, making real-time 3D graphics accessible directly in the browser. It provides a complete scene graph with cameras, lights, geometries, and materials — powering everything from data visualizations to interactive games.' },
  { sw: 'Sw_blender',    cap: 'Blender',      logo: '/Skills/blender.png',      label: 'Blender',      hoverColor: '#E87D0D', desc: 'Blender is a professional open-source 3D creation suite covering the full pipeline from modeling and rigging to animation, simulation, and rendering. Its Cycles and EEVEE render engines produce photorealistic and real-time output, while Python scripting enables custom tool development.' },
  { sw: 'Sw_nodejs',     cap: 'Nodejs',       logo: '/Skills/nodedotjs.png',    label: 'Node.js',      hoverColor: '#339933', desc: 'Node.js is a server-side JavaScript runtime built on Chrome\'s V8 engine that enables non-blocking, event-driven I/O for highly scalable network applications. It unifies front and backend development in a single language and powers REST APIs, real-time WebSocket servers, and CLI tooling via the vast npm ecosystem.' },
  { sw: 'Sw_python',     cap: 'Python',       logo: '/Skills/python.png',       label: 'Python',       hoverColor: '#f6fa01', desc: 'Python is a high-level, readable language that spans web development, data science, machine learning, and automation. Its clean syntax lowers the barrier to prototyping while mature frameworks like FastAPI, NumPy, and Pandas give it serious production credibility.' },
  { sw: 'Sw_c',          cap: 'C',            logo: '/Skills/c.png',            label: 'C',            hoverColor: '#0d75ec', desc: 'C is a foundational systems programming language that provides direct memory access and minimal runtime overhead, making it the language of choice for operating system kernels and embedded firmware. Writing in C builds a deep understanding of memory layout, pointers, and hardware interaction that informs all higher-level development.' },
  { sw: 'Sw_raspberry',  cap: 'Raspberry_pi', logo: '/Skills/raspberrypi.png',  label: 'Raspberry Pi', hoverColor: '#C51A4A', desc: 'Raspberry Pi is a credit-card-sized single-board computer running Linux, designed for learning, prototyping, and embedded deployment. It bridges the physical and digital worlds — connecting sensors, motors, and displays through GPIO pins and serving as an IoT gateway, media server, or robotics controller.' },
  { sw: 'Sw_mqtt',       cap: 'MQTT',         logo: '/Skills/mqtt.png',         label: 'MQTT',         hoverColor: '#660066', desc: 'MQTT is a lightweight publish/subscribe messaging protocol engineered for constrained IoT devices operating over low-bandwidth or unreliable networks. Brokers like Mosquitto route messages between sensors and backend services using topic hierarchies and configurable QoS delivery guarantees.' },
  { sw: 'Sw_mongodb',    cap: 'MongoDB',      logo: '/Skills/mongodb.png',      label: 'MongoDB',      hoverColor: '#47A248', desc: 'MongoDB is a document-oriented NoSQL database that stores data in flexible BSON format, freeing teams from rigid table schemas as requirements evolve. Its horizontal sharding, aggregation pipelines, and rich query language make it a strong fit for applications that need to scale reads and writes independently.' },
  { sw: 'Sw_mysql',      cap: 'MySQL',        logo: '/Skills/mysql.png',        label: 'MySQL',        hoverColor: '#00758F', desc: 'MySQL is the world\'s most popular open-source relational database, providing ACID-compliant transactions, optimized B-tree indexing, and a mature SQL dialect trusted by millions of applications. Its replication and partitioning features make it a reliable backbone for everything from small projects to high-traffic web platforms.' },
  { sw: 'Sw_docker',     cap: 'Docker',       logo: '/Skills/docker.png',       label: 'Docker',       hoverColor: '#2496ED', desc: 'Docker packages applications together with all their dependencies into portable containers that run identically across development, staging, and production. Its layered image builds accelerate CI/CD pipelines, while Docker Compose orchestrates multi-service environments locally with a single command.' },
  { sw: 'Sw_html',       cap: 'HTML',         logo: '/Skills/html5.png',        label: 'HTML',         hoverColor: '#E34F26', desc: 'HTML is the standard markup language that gives every web page its structure and semantic meaning. Elements like headings, landmarks, forms, and media tags form the foundation browsers parse and render, while semantic choices directly influence accessibility, SEO, and how assistive technologies interpret content.' },
  { sw: 'Sw_css',        cap: 'CSS',          logo: '/Skills/css3.png',         label: 'CSS',          hoverColor: '#1572B6', desc: 'CSS is the styling language that transforms raw HTML into visually polished, responsive interfaces. Through custom properties, flexbox, grid layout, and keyframe animations it controls every aspect of typography, color, spacing, and motion — making design both precise and adaptable across any screen size.' },
  { sw: 'Sw_javascript', cap: 'Javascript',   logo: '/Skills/javascript.png',   label: 'JavaScript',   hoverColor: '#F7DF1E', desc: 'JavaScript is the universal scripting language of the web, running natively in every modern browser and on the server via Node.js. It enables dynamic DOM manipulation, asynchronous data fetching through the Fetch API and Promises, and complex application logic — forming the interactive backbone of virtually every web experience built today.' },
  { sw: 'Sw_git',        cap: 'Git',          logo: '/Skills/git.png',          label: 'Git',          hoverColor: '#F05032', desc: 'Git is the industry-standard distributed version control system that tracks every change in a project\'s history with cryptographic integrity. Branching, merging, and rebasing workflows let entire teams collaborate on the same codebase simultaneously without overwriting each other\'s work or losing any previous state.' },
  { sw: 'Sw_postman',    cap: 'Postman',      logo: '/Skills/postman.png',      label: 'Postman',      hoverColor: '#FF6C37', desc: 'Postman is a collaborative API platform that provides an intuitive interface for designing, testing, and documenting HTTP endpoints at every stage of development. It supports automated test scripts, dynamic environment variables, and mock servers — streamlining the full API lifecycle from initial design through production monitoring.' },
]
